https://wikidocs.net/book/2788

# 03. 선형 회귀(Linear Regression)

## 2. 자동 미분(Autograd) 실습하기

In [1]:
import torch

In [3]:
w = torch.tensor(2.0, requires_grad=True)

In [4]:
y = w**2
z = 2*y +5

In [5]:
z.backward()

In [6]:
print('수식을 w로 미분한 겂 : {}'.format(w.grad))

수식을 w로 미분한 겂 : 8.0


# 04. nn.Module로 구현하는 선형 회귀

## 1. 단순 선형 회귀 구현하기

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [20]:
torch.manual_seed(1)

In [21]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [35]:
# 모델을 선언 및 초기화, 단순 선형 회귀 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1,1)

In [29]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


In [37]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [38]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    # H(x) 게산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x)를 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W 와 b를 업데이트
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 33.679783
Epoch  100/2000 Cost: 0.223159
Epoch  200/2000 Cost: 0.137899
Epoch  300/2000 Cost: 0.085213
Epoch  400/2000 Cost: 0.052656
Epoch  500/2000 Cost: 0.032539
Epoch  600/2000 Cost: 0.020107
Epoch  700/2000 Cost: 0.012425
Epoch  800/2000 Cost: 0.007678
Epoch  900/2000 Cost: 0.004744
Epoch 1000/2000 Cost: 0.002932
Epoch 1100/2000 Cost: 0.001812
Epoch 1200/2000 Cost: 0.001119
Epoch 1300/2000 Cost: 0.000692
Epoch 1400/2000 Cost: 0.000427
Epoch 1500/2000 Cost: 0.000264
Epoch 1600/2000 Cost: 0.000163
Epoch 1700/2000 Cost: 0.000101
Epoch 1800/2000 Cost: 0.000062
Epoch 1900/2000 Cost: 0.000039
Epoch 2000/2000 Cost: 0.000024


In [39]:
# 임의의 입력 4를 선언
new_var = torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)# forward 연산
# Y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9902]], grad_fn=<AddmmBackward>)


In [40]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9943]], requires_grad=True), Parameter containing:
tensor([0.0128], requires_grad=True)]


## 다중 선형 회귀 구현하기

In [41]:
import torch
import torch.nn as nn
import torch.nn.functional as f

In [55]:
torch.manual_seed(1)

In [56]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [57]:
# 모델을 선언 및 초기화, 다중 선형 회귀 이므로 input_dim=3, output_dim=1.
model = nn.Linear(3, 1)

In [58]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [59]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [64]:
num_epochs = 10000

for epoch in range(num_epochs + 1):
    
    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 계선
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, num_epochs, cost.item()
        ))

Epoch    0/10000 Cost: 0.199752
Epoch  100/10000 Cost: 0.198930
Epoch  200/10000 Cost: 0.198148
Epoch  300/10000 Cost: 0.197388
Epoch  400/10000 Cost: 0.196674
Epoch  500/10000 Cost: 0.195989
Epoch  600/10000 Cost: 0.195327
Epoch  700/10000 Cost: 0.194704
Epoch  800/10000 Cost: 0.194097
Epoch  900/10000 Cost: 0.193519
Epoch 1000/10000 Cost: 0.192972
Epoch 1100/10000 Cost: 0.192443
Epoch 1200/10000 Cost: 0.191937
Epoch 1300/10000 Cost: 0.191451
Epoch 1400/10000 Cost: 0.190982
Epoch 1500/10000 Cost: 0.190535
Epoch 1600/10000 Cost: 0.190104
Epoch 1700/10000 Cost: 0.189689
Epoch 1800/10000 Cost: 0.189292
Epoch 1900/10000 Cost: 0.188909
Epoch 2000/10000 Cost: 0.188540
Epoch 2100/10000 Cost: 0.188179
Epoch 2200/10000 Cost: 0.187842
Epoch 2300/10000 Cost: 0.187504
Epoch 2400/10000 Cost: 0.187183
Epoch 2500/10000 Cost: 0.186876
Epoch 2600/10000 Cost: 0.186588
Epoch 2700/10000 Cost: 0.186299
Epoch 2800/10000 Cost: 0.186021
Epoch 2900/10000 Cost: 0.185746
Epoch 3000/10000 Cost: 0.185491
Epoch 31

In [66]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.4162]], grad_fn=<AddmmBackward>)


In [63]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


# 05. 클래스로 파이토치 모델 구현하기

## 1. 모델을 클래스로 구현하기

In [67]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)
        
    def forward(self, x):
        return self.linear(x)

In [68]:
model = LinearRegressionModel

In [69]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [70]:
model = MultivariateLinearRegressionModel()

## 2. 단순 선형 회귀 클래스로 구현하기

In [71]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [72]:
torch.manual_seed(1)

In [73]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [79]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)
        
    def forward(self, x):
        return self.linear(x)

In [80]:
model = LinearRegressionModel()

In [81]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [82]:
num_epochs = 2000
for epoch in range(num_epochs + 1):
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 18.562185
Epoch  100/2000 Cost: 0.128051
Epoch  200/2000 Cost: 0.079128
Epoch  300/2000 Cost: 0.048896
Epoch  400/2000 Cost: 0.030215
Epoch  500/2000 Cost: 0.018671
Epoch  600/2000 Cost: 0.011538
Epoch  700/2000 Cost: 0.007129
Epoch  800/2000 Cost: 0.004406
Epoch  900/2000 Cost: 0.002722
Epoch 1000/2000 Cost: 0.001682
Epoch 1100/2000 Cost: 0.001040
Epoch 1200/2000 Cost: 0.000642
Epoch 1300/2000 Cost: 0.000397
Epoch 1400/2000 Cost: 0.000245
Epoch 1500/2000 Cost: 0.000152
Epoch 1600/2000 Cost: 0.000094
Epoch 1700/2000 Cost: 0.000058
Epoch 1800/2000 Cost: 0.000036
Epoch 1900/2000 Cost: 0.000022
Epoch 2000/2000 Cost: 0.000014
